server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: QUIZ-SERVICE
            uri: lb://QUIZ-SERVICE
            predicates:
              - Path=/quiz/**

          - id: QUESTION-SERVICE
            uri: lb://QUESTION-SERVICE
            predicates:
              - Path=/question/**